openapi: 3.1.0
info:
  title: 3Days - 인증 API
  version: 1.0.0
  description: 사용자 인증, 회원가입, 토큰 관리를 위한 API

tags:
  - name: authentication
    description: 인가, 인증에 관한 작업들

paths:
  /auth/phone:
    post:
      summary: 휴대폰 번호 인증 요청
      description: 사용자의 휴대폰 번호로 인증 코드를 발송합니다.
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneRequest'
      responses:
        '200':
          description: 인증 코드가 성공적으로 발송됨
        '400':
          description: 유효하지 않은 휴대폰 번호

  /auth/verify:
    post:
      summary: 인증 코드 확인
      description: 사용자가 입력한 인증 코드의 유효성을 확인합니다.
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationRequest'
      responses:
        '200':
          description: 휴대폰 번호 인증 성공
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/TokenResponse'
                  - $ref: '#/components/schemas/RegisterTokenResponse'
        '400':
          description: 유효하지 않은 인증 코드

  /auth/register:
    post:
      summary: 회원가입 완료
      description: Register Token과 사용자 프로필 정보를 이용하여 회원가입을 완료합니다.
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '400':
          description: 유효하지 않은 Register Token 또는 프로필 정보

  /auth/refresh:
    post:
      summary: 액세스 토큰 갱신
      description: 리프레시 토큰을 이용하여 새로운 액세스 토큰을 발급받습니다.
      tags:
        - authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshRequest'
      responses:
        '200':
          description: 새로운 액세스 토큰 발급 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: 유효하지 않은 리프레시 토큰

components:
  schemas:
    PhoneRequest:
      type: object
      properties:
        phone:
          type: string
          pattern: '^010-\d{4}-\d{4}$'
          minLength: 13
          maxLength: 13
          example: "010-1234-5678"
      required:
        - phone
      additionalProperties: false
      description: 휴대폰 번호 인증 요청 정보

    VerificationRequest:
      type: object
      properties:
        phone:
          type: string
          pattern: '^010-\d{4}-\d{4}$'
          minLength: 13
          maxLength: 13
          example: "010-1234-5678"
        code:
          type: string
          pattern: '^\d{6}$'
          minLength: 6
          maxLength: 6
          example: "123456"
      required:
        - phone
        - code
      additionalProperties: false
      description: 인증 코드 확인 요청 정보

    RegisterRequest:
      type: object
      properties:
        registerToken:
          type: string
          format: jwt
          minLength: 1
        profile:
          $ref: '#/components/schemas/Profile'
      required:
        - registerToken
        - profile
      additionalProperties: false
      description: 회원가입 완료 요청 정보

    RefreshRequest:
      type: object
      properties:
        refreshToken:
          type: string
          format: jwt
          minLength: 1
      required:
        - refreshToken
      additionalProperties: false
      description: 토큰 갱신 요청 정보

    TokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          format: jwt
          minLength: 1
        refreshToken:
          type: string
          format: jwt
          minLength: 1
      required:
        - accessToken
        - refreshToken
      additionalProperties: false
      description: 액세스 토큰 및 리프레시 토큰 응답

    RegisterTokenResponse:
      type: object
      properties:
        registerToken:
          type: string
          format: jwt
          minLength: 1
      required:
        - registerToken
      additionalProperties: false
      description: Register Token 응답

    Profile:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        email:
          type: string
          format: email
          maxLength: 255
      required:
        - name
        - email
      additionalProperties: false
      description: 사용자 프로필 정보

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Bearer 토큰을 이용한 인증

security:
  - BearerAuth: []
